### ISSUE TITLE
 Problem about excluding files

### ISSUE THREAD

**Issue by fx1994** [stevenblair/rapid61850#2]
When I use the python interface, I only exclude the main.c , is it right?And do I have to exclude other files,  And I check both the debug and release when excluding, what does your “uncheck debug or release” mean, I did not understand it.
![image](https://cloud.githubusercontent.com/assets/18289144/14305837/1fd190a2-fbf3-11e5-95ab-6526151414f8.png)
![image](https://cloud.githubusercontent.com/assets/18289144/14305841/33f0328c-fbf3-11e5-9196-9a0179f95eed.png)

**Comment by fx1994** [comment]
![image](https://cloud.githubusercontent.com/assets/18289144/14306180/fe1eaa2c-fbf6-11e5-970b-61c0e8d6a008.png)
And when I use the Python interface, should the HIGH_LEVEL_INTERFACE set to 1?

**Comment by stevenblair** [comment]
There are several example main*.c files which should be excluded from the build in this case. Yes, that was a mistake - you should check those boxes, rather than unchecking them.

Yes, `HIGH_LEVEL_INTERFACE`  should be set to `1` to use the Python interface.
