### ISSUE TITLE
Problem about running the main.py

### ISSUE THREAD

**Issue by fx1994** [stevenblair/rapid61850#4]
Thank you for the answers of the privious questions.
.
When I copy the _rapid61850.pyd to the python_interface project, and run the main.py, I met this error.
![image](https://cloud.githubusercontent.com/assets/18289144/14353069/130717bc-fd0a-11e5-915d-59fd94944916.png)

How can I fix it?

Thank you!

**Comment by stevenblair** [comment]
I'm not sure. What C/C++ compiler are you using? It might be related to this issue: http://stackoverflow.com/a/4113037/57743

**Comment by fx1994** [comment]
![image](https://cloud.githubusercontent.com/assets/18289144/14355004/1f95e2e4-fd12-11e5-9476-40e1118ba026.png)
C/C++ compiler is like this.

**Comment by fx1994** [comment]
When I use the scd.xml from your code as an input scd file, I run the main.py and get the result like this. Is it right?
![image](https://cloud.githubusercontent.com/assets/18289144/14356091/04582e48-fd16-11e5-9432-95a14017df94.png)

**Comment by stevenblair** [comment]
Yes, that is working correctly. If you check with Wireshark, you should be able to look at the GOOSE messages being sent by the example code.

You may also need to point to a different network interface for your purposes. If so, you would adjust this line of code as required: https://github.com/stevenblair/rapid61850/blob/master/c/src/interface.c#L56 (I will add some documentation about this to the main README file.)

**Comment by fx1994** [comment]
When I use my scd file , how can I adjust the main.py or other files to print the values from  goose in RTDS? Now I met this error.
![image](https://cloud.githubusercontent.com/assets/18289144/14372130/3efea7f2-fd70-11e5-8daf-b7804ec85973.png)

And I set this to 0, is it right?
![image](https://cloud.githubusercontent.com/assets/18289144/14372155/8e1e8a46-fd70-11e5-8bc7-3ef34f936833.png)

And this address what should I set to?
![image](https://cloud.githubusercontent.com/assets/18289144/14372175/c200ab82-fd70-11e5-92e2-8a98c65465c9.png)

Thank you!

**Comment by stevenblair** [comment]
You need to check the Python file generated by SWIG to get the function and data structure names which are valid for your data model. The example main.py file will almost certainly not match this.

Yes, `JSON_INTERFACE` should be set to 0 in this case. The local MAC address can be changed, but it's not necessary.

**Comment by fx1994** [comment]
When I use the scd.xml from your code as an input scd file and run the main.py, I didn't get a GOOSE message from  the  Wireshark . Why? And when should I get the GOOSE message, build the C project or run the main.py?
![image](https://cloud.githubusercontent.com/assets/18289144/14387299/5af95d38-fddb-11e5-95be-4b8fc4331665.png)
![image](https://cloud.githubusercontent.com/assets/18289144/14387305/648237da-fddb-11e5-8e1f-4ea1321bb477.png)

Thank you！

**Comment by stevenblair** [comment]
It might be that your network interface does not show local traffic. Try another interface, or install VirtualBox and use the virtual network interface it installs in your OS.

**Comment by fx1994** [comment]
When I use the scd.xml from your code as an input scd file and run the main.py on another computer，why there is no response in console?
![image](https://cloud.githubusercontent.com/assets/18289144/14419298/77d3431a-fff7-11e5-89f3-f47d4977ded9.png)

Thank you!

**Comment by fx1994** [comment]
![image](https://cloud.githubusercontent.com/assets/18289144/14419397/35e58fb6-fff8-11e5-89c2-e5fa4a37e5b6.png)
It was always importing test modules ,and it didn't run out a result?

**Comment by stevenblair** [comment]
It's very difficult to answer - there are several things which must be set up correctly for communications between devices to work. The screenshot suggests that you are not attempting to read the incoming GOOSE data anyway - again, you need to customise main.py for your own application.

I'm not sure what you mean from your second question.

**Comment by fx1994** [comment]
The second question:
When I use the scd.xml from your code as an input scd file and run the main.py on another computer，the response in console is like this, it is importing test modules all the time and can't continue to next step. So I can't get the GOOSEmessage. Why ?
![image](https://cloud.githubusercontent.com/assets/18289144/14425348/1b875174-0019-11e6-9bf3-d0b91c46cd43.png)

**Comment by stevenblair** [comment]
I don't know. Something is clearly configured differently on your second machine - are you running PyUnit?

**Comment by fx1994** [comment]
Yes, I use the PyUnit．

**Comment by fx1994** [comment]
Then  I use my scd file from RTDS. Why when I don't run the RTDS and no GOOSE message is sent, but I also can receive a result when I run the main.py?

**Comment by stevenblair** [comment]
That's impossible to answer without seeing your Python code, and without knowing the full details of your configuration.

**Comment by fx1994** [comment]
Thank you for your answers to the all the questions  before. Now I can run the main.py rightly and I can use the Wireshark to find the GOOSE message sent by your example code. However, I find that it seems like you print the length of the GOOSE message in main.py, do you know how can I print the values of the GOOSE message sent by your example code ?
This is the values of GOOSE message according to Wireshark.
![image](https://cloud.githubusercontent.com/assets/18289144/14456435/7b02590a-00d7-11e6-971f-2d535b7d16fa.png)

**Comment by stevenblair** [comment]
The example main.py file shows exactly how to do this from Python: https://github.com/stevenblair/rapid61850/blob/master/python_interface/main.py#L11

Obviously, you will need to modify the code to match your data model.
