### ISSUE TITLE
Problem about decode GOOSE

### ISSUE THREAD

**Issue by jsh1234** [stevenblair/rapid61850#5]
Dear sir
Could you please tell me how to receive or decode GOOSE packet using python? The example main.py file only shows how to send GOOSE, however, it does not show how to receive GOOSE packet.
https://github.com/stevenblair/rapid61850/blob/master/python_interface/main.py

What's more, what's the mechanism of getting data from GOOSE packet? Does rapid61850 support callback function to decode GOOSE packet.

I use rapid61850 to send GOOSE packet successfully, and send my data out. So I want to know how to receive data that sending by other device.

PS: I don't use SV.
Thanks

**Comment by stevenblair** [comment]
At the moment, you can use the `rapid61850.readPacket()` and `rapid61850.readPacketTimeout()` functions to check for packets. These are defined in interface.c. `readPacket()` waits until a packet (which may be GOOSE, SV, or other data) arrives, and attempts to processes it. `readPacketTimeout()` looks for a packet, but will return after the default timeout (specified in the `pcap_open_live()` call in interface.c) if none are ready.

So the dataset callbacks are not supported from the Python interface at the moment.

**Comment by jsh1234** [comment]
Thanks for your answer
Could you please give me some easy example about how to use the two function, and get the data in the packet

**Comment by stevenblair** [comment]
Just call the functions :)

Then look at the values in your data model, e.g.: https://github.com/stevenblair/rapid61850/blob/master/python_interface/main.py#L11

You can check the return value of `readPacketTimeout()` to check if a packet was received (but that does not guarantee that it was a valid GOOSE or SV packet).

**Comment by jsh1234** [comment]
Thanks for your help
The return value of readPacket() is 0, and  readPacketTimeout() is 1; but I can't get the data value. I got the packet? 
When I get the packet? Do I need a function to decode the packet? Like the code to send GOOSE followed?  https://github.com/stevenblair/rapid61850/blob/master/python_interface/main.py#L8

I use the following code to send GOOSE
    rapid61850.cvar.IED1.P1.CTRL1.OUT_GTNET_GEN_GGIO_2.AnIn.mag.f=3.1415926;
    rapid61850.interface_gse_send_IED1_CTRL1_Gcb01(1, 512);

And I use the following code to read data, but it's zero. I am right?
    rapid61850.cvar.IED2.P1.CTRL2.IN_GTNET_GEN_GGIO_1.AnIn.mag.f
    rapid61850.cvar.IED2.P1.CTRL2.IN_GTNET_GEN_GGIO_2.AnIn.mag.f

Thanks

**Comment by stevenblair** [comment]
Sorry, if you are looking for decoded GOOSE values, there is a special data structure for these with prefix `gse_inputs_`. An example for the C/C++ interface is: `float inputValue = D1Q1SB4.S1.C1.RSYNa_1.gse_inputs_ItlPositions.E1Q1SB1_C1_Positions.C1_TVTR_1_Vol_instMag.f;`. Similarly, you can look at the Python file generated by SWIG to find the exact data structures to access from your Python file.

**Comment by jsh1234** [comment]
Do I need to call function to receive and decode GOOSE packet? like the code to send GOOSE?
What's the return value of readPacket() and readPacketTimeout() if I receive a GOOSE?

**Comment by jsh1234** [comment]
Thanks for your help.
Now I use ### _rapid61850.readPacket(),rapid61850.readPacketTimeout()_,I can get the packet.

And I can get the digital value by using the following code.
_rapid61850.cvar.IED1.P1.CTRL1.IN_GTNET_GEN_GGIO_1.gse_inputs_Gcb02.IED2_CTRL2_GOOSE_outputs_2.CTRL2_OUT_GGIO_1_IntIn_stVal _

Howerver,  I can't get the analog value using the similar code followed, the result is 0.0, obviously, it's not right. Could you please tell me how to deal with it.
_rapid61850.cvar.IED1.P1.CTRL1.IN_GTNET_GEN_GGIO_1.gse_inputs_Gcb02.IED2_CTRL2_GOOSE_outputs_2.CTRL2_OUT_GGIO_2_AnIn_mag.f_

**Comment by stevenblair** [comment]
It's difficult to be certain, but the IED naming looks inconsistent compared to your earlier comment. You should be accessing the data model for the receiving IED only. So, if IED1 is sending and IED2 is receiving, it should be something like:

rapid61850.cvar.IED2.P1.CTRL1.IN_GTNET_GEN_GGIO_1.gse_inputs_Gcb02.IED1_CTRL2_GOOSE_outputs_2.CTRL2_OUT_GGIO_2_AnIn_mag.f

or some other variation that fits your data structure.

**Comment by jsh1234** [comment]
Thanks for your answer
IED1 is the PC-soft, IED2 is the external device, the scd file contain the two device.
from the struct "gse_inputs_Gcb01", I can find IED2_CTRL2_GOOSE_outputs_2---CTRL2_OUT_GGIO_1_IntIn_stVal, CTRL2_OUT_GGIO_2_AnIn_mag; I think the data structure is right.
Because I can get the digital value, I don't know why I can't get the analog value.

**Comment by jsh1234** [comment]
What's the result of rapid61850.readPacket()? It's 0 no matter I get the packer or not?
And the result of rapid61850.readPacketTimeout() ? What's the meaning of 0? 1?
Does rapid61850  support block or socket like other protocol?
Thanks

**Comment by stevenblair** [comment]
If you look at the code in interface.c, `readPacket()` should return 0 when a packet is processed. Similarly, `readPacketTimeout()` should return 1 if one packet was processed.

There's no direct support for non-blocking sockets. You could of course implement your own system, or even replace the low level network interface completely (e.g. with raw sockets rather than pcap).
